version: "3.3"
services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: movies-app-proxy:latest
    restart:  unless-stopped
    container_name: movies-app_proxy
    depends_on:
      - api
    expose:
      - 80
    ports:
      - "3001:80"
  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    image: movies-app_api:latest
    restart: unless-stopped
    container_name: movies-app_api
    depends_on: 
      - database
    environment:
      - DB_CONNECTION_STRING=Data Source=database;Database=MoviesApp;User ID=sa;Password=Au471pn*%122;TrustServerCertificate=true

  database:
    image: mcr.microsoft.com/mssql/server
    container_name: movies-app_database
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Au471pn*%122"
    expose:
      - 1433
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
volumes:
  sql-data:    
